"""One-shot TASK-17 patch selecting the containerized code generator."""

import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
package_path = root / "frontend/package.json"
package = json.loads(package_path.read_text(encoding="utf-8"))
package["scripts"]["api:generate"] = "node ../scripts/generate_api_sdk.mjs"
package["scripts"]["api:check"] = (
    "npm run api:generate && git diff --exit-code -- ../docs/api/openapi.json src/generated/api"
)
package["devDependencies"].pop("@hey-api/openapi-ts", None)
package["devDependencies"].pop("orval", None)
package_path.write_text(json.dumps(package, indent=2) + "\n", encoding="utf-8", newline="\n")

log_path = root / "docs/implementation-log.md"
log = log_path.read_text(encoding="utf-8")
log = log.replace(
    "- `@hey-api/openapi-ts` 0.99.0 is pinned exactly as a frontend development dependency for\n  deterministic OpenAPI-to-TypeScript generation. No backend runtime dependency changed.",
    "- No npm dependency is added for code generation. The SDK is generated by the pinned\n  `openapitools/openapi-generator-cli:v7.24.0` container using the `typescript-fetch` generator.\n  Hey API 0.99.0/0.97.0 and Orval 8.23.0 were evaluated and rejected because npm audit exposed\n  high or moderate vulnerable dependency chains. No backend runtime dependency changed.",
)
log_path.write_text(log, encoding="utf-8", newline="\n")
print("Configured pinned OpenAPI Generator v7.24.0 container; no npm codegen dependency")
